server:
  port: 8762


eureka:
  instance:
    hostname: 127.0.0.1
  center:
    port: 8761
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.center.hostname}:${eureka.center.port}/eureka/

spring:
  application:
    name: service-hi
