server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/

spring:
  application:
    name: service-hi
  zipkin:
    locator:
      discovery:
        enabled: true
        service-id: server-zipkin
