server:
  port: 8765
spring:
  application:
    name: service-feign

eureka:
  center:
    port: 8761
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.center.hostname}:${eureka.center.port}/eureka/

feign:
  hystrix:
    enabled: true