server:
  port: 8766
spring:
  application:
    name: service-ribbon
  zipkin:
    locator:
      discovery:
        enabled: true
        service-id: server-zipkin

eureka:
  center:
    port: 8761
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.center.hostname}:${eureka.center.port}/eureka/

